Convert types to .d.ts files
nolanlawson/emoji-picker-element pull request #61
Opened 2020-10-27 19:30 UTC by mrdrogdrog

Good evening,

Some days ago I found out, that the picker types don't have a signature for `removeEventListener`, so I was about to create an issue. But then I though "Why don't you fix that?". Then I saw your types and the dummy classes and five shaved yaks later I'm here. (Yes I read the contribution guidelines.)

This PR:
- Converts all .ts files to .d.ts files and removes the dummy implementations.
- Changes the typedoc call to also include the .d.ts files
- Changes the generateTOC script, so it still finds the scripts
- Add signatures for removeEventListener

Feel free to review!

2020-11-01 23:59 UTC, nolanlawson commented
This is a great change, thank you. I'm not a super-duper TypeScript expert, so that's why I did things the way I did. :slightly_smiling_face:

Nonetheless, I actually did realize recently that I could still use typedoc with just .d.ts files and `--includeDeclarations`, so I was considering making this change myself. But you saved me the trouble. So thanks a ton! :heart:

2020-11-02 00:00 UTC, nolanlawson commented on package.json
> +    "build:types": "cp ./src/types/*.d.ts ./",
We might as well just put the .d.ts files at the top level, but I can change that later

2020-11-02 00:02 UTC, nolanlawson requested changes
Unfortunately it looks like this messes up the README a bit due to how typedoc works. E.g. some methods that are supposed to return `void` now return `any`, and the picker options and defaults are all gone... I wonder if there is still a way to fix this with just `.d.ts` files, or if it's a limitation of typedoc and therefore we should stick to dummy TS files. Another tricky part is that typedoc is out-of-date, and upgrading results in a messed-up README file... this may need some additional work :confused:

2020-11-02 00:06 UTC, nolanlawson commented
^ Short-term fix for the `removeEventListener` issue

2020-11-02 06:49 UTC, mrdrogdrog commented
I think I can solve the remaining issues :)

Please stay tuned

2020-11-02 06:50 UTC, mrdrogdrog commented
The readme looked fine when I tested the PR 😅
But I'll dig deeper and try to solve the issues :)

2020-11-02 19:59 UTC, mrdrogdrog commented
Okay I did some researches:
- `.d.ts` files can't handle default values. You could put them into the docs, but that is kinda ugly.
- The only `any` type I found was at the setter. But that's [okay](https://stackoverflow.com/questions/58012216/what-is-the-correct-type-of-a-set-function-in-typescript/58012306#58012306)

But I could still fix the `@ts-ignore` stuff.

2020-11-02 20:10 UTC, mrdrogdrog commented
BTW: `@ts-ignore` was needed, because you didn't add a implementation for `addEventListener`. Only the signature.

2020-11-03 20:55 UTC, nolanlawson commented
Ah, that's too bad. Thanks for doing the research, though! Looks like we should probably stick with the `.ts` files for now then. I appreciate the fix!

2020-11-03 20:57 UTC, nolanlawson approved these changes

2020-11-03 20:58 UTC, merged